---
title: "Research Proposal"
author: "Krisanat Anukarnsakulchularp"
format: html
---

Use the old research proposal and split it into 2 project, where first project is more exploration framework with applicaiton and second project is more idm with policy. Think more in general case of multivariate spatio-temporal data.

Think about visualisation

- jittered dot for the co-located RACF

- animbook

    - sankey

    - map (https://www.nytimes.com/video/us/politics/100000010652139/inside-trumps-deportation-machine.html)

Have a more concrete question

Talk about EDA and IDM in background as well 


# Background

Recently, exploring and analysing large network structure data has sparked more interest in the health field, particularly within emergency medical services (EMS) and ambulance systems. This increase is largely due to an advancement in technology, such as the Global Positioning System (GPS), mobile devices, and remote sensing, which have significantly contribute ot the precision and volume of spatio-temporal data. This type of data captures information on both spatial and temporal context. The spatial component describes the location or spatial geometry, while the temporal component records time information such as a timestamp or time interval.

The emergency medical services and ambulance systems have an important role in ensuring that patient transfers are performed effectively and in a timely manner. This is especially important for an older population, where the delay could lead to an increase in health risk. Older individuals often require continuous support, including 24-hour care, assistance with daily tasks, and medical supervision. Thus, many reside in the residential aged care facilities (RACFs), which are specifically designed to provide this comprehensive care. RACFs frequently rely on the ambulance services to facilitate the transfer of an individual to the hospital. It can be an acute emergency or planned/scheduled medical appointments. The increase in demand for these transfers is driven by population ageing. It put incredible pressure on the ambulance resource and highlights the need for efficient planning and utilisation of the service.

To gain insight into the transfer patterns, the data exploration, along with network representations linking RACFs and hospitals, provides a powerful framework. Network-based representations of the data are naturally perceived as relational, and people often associate the flow and connections with it. However, most network research tends to be conducted homogeneously, focusing primarily on the network topological properties while overlooking other important pieces of information, for example, the association between variables. While network representation is a powerful tool, especially for the transfers data, overemphasising network typology can lead to the neglect of the fundamental principles of data exploration. Where one encourages a free investigation of the data to uncover patterns and unexpected results. Simple but informative analyses, such as examining variable distribution, temporal trends, or even bivariate relationships, can reveal a lot of insights into transfer frequency, efficiency, and demand that are often masked by the network structure. Integrating data exploration with network-based approaches, therefore, allows for a better understanding of the RACF and hospital transfer.

Studying how infectious diseases spread throughout the network (link between RACFs and hospitals) is important because the older population tend to face a higher risk of mortality during the outbreaks. These patient transfers between facilities create ways for the disease to be transmitted across the systems, leading to rapid spread. Traditional compartmental infectious disease models assuming homogeneous or static structure do not adequately capture networks that change over time. In reality, ambulance transfers are highly dynamic, where these connections between facilities can change in response to the demand, constraints, and even outbreak conditions. Understanding these transmission dynamics is therefore crucial for devising effective policies for stopping the spread of the disease. Combining a data exploration framework, which helps understand how the transfer network changes over time, with dynamic modelling that assesses how these changes affect the disease spread, is critical for identifying high-risk facilities, transfer connections, and periods.


## Project 1: A Multivariate Spatio-Temporal Network Data Exploration Framework with Application to Ambulance Transfer Demand and Efficiency

As multivariate spatio-temporal network data became more accessible, understanding their structure and dynamics is key to effective decision-making. By integrating exploratory data analysis (EDA) with network-based representations, the framework will support an examination of the association between variables, temporal changes, and structural differences within the datasets. The framework consists of four key processes: data cleaning, subsetting, visualising, and modelling.

Data cleaning is the first stage of a reliable analysis. Spatio-temporal network data present unique challenges, including inconsistent temporal records, duplicated records, and spatial inaccuracies arising from data processing. On top of that, the network structure, nodes, edges, and their attributes must be preserved during cleaning. This stage typically involves tools such as `dplyr` for manipulating the data, `tsibble` for validating the temporal inconsistency, `sf` for checking the coordinate inaccuracies, and `network`/`igraph` for keeping the network structure. (Will need to talk about tidygraph)

Data subsetting is used to extract a subset of data based on spatial, temporal and multivariate variables. It includes stratification by time periods, regions, or multivariate information, as well as filtering based on network attributes or variable information. It enables a deeper exploration of different sections of data for uncovering more insights.

Data visualisation helps reveal patterns, anomalies and relationships that may not be apparent from numerical summaries alone. Also, spatio-temporal network data are often viewed as connections or flows between nodes/locations, and network-based visualisation allows for easier communication to a broader audience. Along with simple exploratory plots, ignoring network representation, such as variable distributions or time series, can add additional insight to the data.

Data modelling is used to quantify patterns identified during the exploration. It includes statistical and spatio-temporal models to capture the temporal variability and spatial dependence, as well as network-based measures describing connectivity, flow, and structural change over time. The modelling results are to confirm the inference observed during the exploration.

(Integrating the old research proposal)

The efficiency of the ambulance transfer is critical in both scheduled and emergency transfer cases to minimise the resources used and affect the patient outcomes. In scheduled transfers, the longer the transfer, the fewer ambulances are available in the system, which potentially limits the number of ambulances available during the peak demand or emergency state. In emergency transfers, it directly influences the outcomes of the patient, especially for time-sensitive conditions such as trauma, cardiac emergencies, and stroke. Analysing ambulance transfer efficiency is therefore crucial for improving the quality of emergency care, ensuring an adequate number of available ambulances, and strengthening the system. In addition, predicting ambulance demand is also important as it allows the services to plan accordingly in different scenarios (e.g. peak demand).


## Project 2: Dynamics Infectious Disease Modelling of Ambulance Network Changes

This focuses on understanding the impact of any changes in the ambulance transfer network on the spread of infectious diseases, particularly among the older populations in residential aged care facilities. Ambulance transfer creates a way in which infections can be transmitted throughout facilities and hospitals. The variations in network structure, caused by changes in transfer demand or constraints, can influence how the disease spreads within the network.

(Dynamics Infectious Disease modelling section)
